### ISSUE TITLE
`option(..., hidden=True)` not compatible with `--show-params`

### ISSUE THREAD

**Issue by themoep** [kdeldycke/click-extra#689] opened 2023-07-07 13:54 UTC
Hi there! 
Using `--show-params` with a hidden option throws a TypeError because `param.get_help_record(ctx)` [returns None when the parameter is hidden](https://github.com/pallets/click/blob/d9af5cfa009c927a96d10ed38a3e37979876a12e/src/click/core.py#L2736).
The cause is that in `print_params` the result of `get_help_record` is [subscripted and not checked for None](https://github.com/kdeldycke/click-extra/blob/main/click_extra/parameters.py#L619).

An example causing this error is as follows:
```python
from click import option, echo
from click_extra import extra_command

@extra_command
@option("--dummy-flag/--no-flag", hidden=True)
def my_cli(dummy_flag):
    echo(f"dummy_flag is {dummy_flag!r}")

if __name__ == "__main__":
    my_cli()
```

Running it with `--show-params` throws a TypeError for click-extra 4.5.0

I could prepare a patch but I am not sure what the intended behavior should be: since click doesn't generate the help record for the hidden parameters, re-implementing this in click_extra for the hidden paramters seems not clean. On the other hand not printing anything in this field for `--show-params` is very counterintuitive as well since the arguments do get parsed. A workaround would be to set hidden False before generating the help record and then resetting it to the previous value.

Am I missing something? Looking forward to your thoughts on this.

**Comment by kdeldycke** [comment] 2023-07-07 15:34
I just added a `Hidden` column to the table produced by `--show-params` for easier troubleshooting.

See: https://github.com/kdeldycke/click-extra/commit/66d5a10d42c1b95fded12ad7cfdaea609259c060

What's left for me to do before closing the issue is implementing a hack to unlock the production of `get_help_record` spec for hidden parameters.

**Comment by kdeldycke** [comment] 2023-07-08 06:53
> What's left for me to do before closing the issue is implementing a hack to unlock the production of `get_help_record` spec for hidden parameters.

Just fixed that in https://github.com/kdeldycke/click-extra/commit/502a9d0269d7d90f0ea92eb93e7058023cbfa705 .

Click Extra is already full of monkey-patch and workarounds, so another one is OK. I'll try to propose a definitive fix upstream in Click later.

**Closed by kdeldycke** 2023-07-08 06:53 UTC
Labels: 🐛 bug
